### ISSUE TITLE
RuntimeError:The size of tensor a (512) must match The size of tensor B (3) at non-singleton Dimension 4

### ISSUE THREAD

**Issue by neil-jinsh-public** [wangle53/TransCD#11]
https://github.com/wangle53/TransCD/blob/be511a1d2e39a8906dc44023e35d310c991de75b/utils/make_dataset.py#L45

Thank you for sharing the code.

I have a question I'd like to answer from you.

At make_dataset.py, line 45, gt adds a dimension, which causes The error"RuntimeError: The size of tensor a (512) must match The size of tensor B (3) at non-singleton Dimension 4". What are the considerations for this step?

Best regards

**Comment by wangle53** [comment]
Adding a dimension to GT is not always necessary which depends on the gt data type of your datasets. In any case, makesure the gt dimensions are correct in shape [Batch, Channel, Hidth, Width]. In your case, it maybe the reason of dismatched shapes between gt and output features. Please print the relative feature shapes and make sure the input tensor shapes are in the same shapes, especially the channel dimension.

**Comment by neil-jinsh-public** [comment]
I print the shape of x1, x2, and gt.  x1 and x2 are transformed from (512, 512, 3) to (3, 512, 512) by function that is transforms.Totensor() . And the dimensions of gt at "gt = np.asarray(gt).astype(np.float)" is (512, 512, 3).  Finally, the shape of x1, x2, gt = data in https://github.com/wangle53/TransCD/blob/be511a1d2e39a8906dc44023e35d310c991de75b/train.py#L76
 is (4,3,512,512) , (4,3,512,512) , (4,512,512,3) respectively.

In my opinion, I think the dimensions of the three pictures(Compare pictures and labels) should be the same. Why is this happening? Please enlighten me, thanks! Thank you for your patience！


The following figure shows that the results of running “If TRANSFORM:”in make_dataset.py once
![image](https://user-images.githubusercontent.com/49297407/182773262-296eecc9-bdd8-4fcd-9873-db98664fa935.png)

**Comment by wangle53** [comment]
The shape of gt should be [B 1 H W]. For the used dataset in our paper, the gt is 1-channel image, hence we add a new dimension during data processing phase.
Do you use your own dataset on TransCD? I think your gt imagess are 3-channel images. Please ensure they are 1-channel images.

**Comment by neil-jinsh-public** [comment]
> The shape of gt should be [B 1 H W]. For the used dataset in our paper, the gt is 1-channel image, hence we add a new dimension during data processing phase. Do you use your own dataset on TransCD? I think your gt imagess are 3-channel images. Please ensure they are 1-channel images.

I using VL_CMU_CD dataset.

**Comment by wangle53** [comment]
before gt = gt[np.newaxis, :, :]; adding this code:  gt = gt[:, :, 0];

**Comment by neil-jinsh-public** [comment]
From what you've explained, I think this kind of modification is helpful, and I also think that artificially reducing the dimensionality of the code will work. Thank you for your guidance.

**Comment by wangle53** [comment]
You are welcome. By the way, from my test, the mask imgs in VL-CMU-CD datase are 1-channel images. I'm not sure if you have changed some code in the submittd code source. Please check your code, make sure the shape of GT is [B 1 H W]
