### ISSUE TITLE
How to generate maskGT in VL_CMU_CD dataset?

### ISSUE THREAD

**Issue by WangDeyu** [wangle53/TransCD#12]
In offered train.txt, the name of label is mask**.png, be the name of label  in original VL_CMU_CD is gt**.png, so how to generate maskGT? can I just change their name?

**Comment by wangle53** [comment]
Please review the introduction of VL-CMU-CD in their paper. In this dataset, for each pair of  sample images, the authors offered two labels, 'gt**.png' for multi-labels and 'mask**.png' consisting of two labels (change and no-change)for change detection. In our experiments, we use mask**.png to supervise change detection task.

**Comment by WangDeyu** [comment]
In the VL-CMU-CD which is downloaded from the baidu link, I don't find any mask**.png.

**Comment by wangle53** [comment]
![mask00](https://user-images.githubusercontent.com/79884379/205527835-d919a24a-b56c-4e27-b4b3-96e136a9c216.png)
Generate mask.png from its corresponding gt.png.

**Comment by wangle53** [comment]
Generate mask.png from its corresponding gt.png.
![gt00](https://user-images.githubusercontent.com/79884379/205528045-6ef51262-ea9c-4ca6-b239-03e054f3deb4.png)
![mask00](https://user-images.githubusercontent.com/79884379/205528050-49207193-b24b-4678-8dd2-1766798eac2d.png)

**Comment by WangDeyu** [comment]
Well, I got it!
