### ISSUE TITLE
Evaluate on an image pair

### ISSUE THREAD

**Issue by arianaa30** [wangle53/TransCD#14]
Interesting work. How can I test the pretrained model on a single image pair instead of testing a whole directory?

Basically given two images I want to get the changed parts.

**Comment by wangle53** [comment]
Thanks for you notice. We didn't provide utilities for testing a single image pair, please you can write a script or revise the provided codes to deliver it.

**Comment by arianaa30** [comment]
Sure. Can you give me some hints? Is it like only changing `test.py`?

**Comment by wangle53** [comment]
Yes, you can revise test.py, please notice that revise dataset.py to adapt your data.
