### ISSUE TITLE
6 ViT models- Pros and Cons?

### ISSUE THREAD

**Issue by arianaa30** [wangle53/TransCD#15]
Can you please give some descriptions about the 6 different models? 
SViT_E1_D1_16, SViT_E1_D1_32, SViT_E4_D4_16, SViT_E4_D4_32, Res_SViT_E1_D1_16 and Res_SViT_E4_D4_16.

How are they different? And which one is faster and more accurate, etc?

**Comment by wangle53** [comment]
‘E' and 'D' denote the transformer layer numbers of the encoder and decoder in SViT, respectively. 'Res' denotes if the proposed TransCD uses ResNet18 pre-extracting image features. The more details can be found from our paper, please.

**Comment by arianaa30** [comment]
Got it thank you!
