### ISSUE TITLE
test.py can not find test.txt

### ISSUE THREAD

**Issue by huntkao** [wangle53/TransCD#2]
using arguments: '--net_cfg SViT_E1_D1_32 --train_cfg CDNet_2014 --save_changemap True'
test.py returns "No such file or directory: './CDNet_2014/data/test.txt' "

**Comment by wangle53** [comment]
you can replace 'test.txt' with 'val.txt' . Note that CDNet2014 doesn't contain a test dataset.

**Comment by huntkao** [comment]
OK.

So I need to make symbolic links from  {$CD2014_ROOT}./dataset/dynamicBackground/boats/input to {$CD2014_ROOT}./dataset/dynamicBackground/boats/t0 and {$CD2014_ROOT}./dataset/dynamicBackground/boats/t1 as indicated in val.txt ?

**Comment by wangle53** [comment]
yes. change dataset path to your own path.

**Comment by huntkao** [comment]
it works.
